### ISSUE TITLE
Cannot install from NPM

### ISSUE THREAD

**Issue by bryanbuchs** [nodef/extra-number#1]
The package folder is empty after running `npm i extra-number`

```
λ ls -al node_modules\extra-number\
total 268
drwxr-xr-x 1 bryan 197609    0 Jul 22 10:12 ./
drwxr-xr-x 1 bryan 197609    0 Jul 22 10:12 ../
-rw-r--r-- 1 bryan 197609 1073 Oct 26  1985 LICENSE
-rw-r--r-- 1 bryan 197609 1772 Jul 22 10:12 package.json
-rw-r--r-- 1 bryan 197609 3429 Oct 26  1985 README.md
```

And if I try to install directly from github with ` npm i git@github.com:nodef/extra-number.git`, I get an error:

```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "github.com:nodef\extra-number.git" as it does not contain a package.json file.
```

**Comment by wolfram77** [comment]
I tried and it does work. Have seen NPM website getting some issues since GitHub acquired it, so i guess it is in process of getting upgraded. I can say i was never good at mathematics in school, so i will be extending this program in some time... learning virology a bit for now.  @bryanbuchs
