### ISSUE TITLE
no var keyword!!! 

### ISSUE THREAD

**Issue by c0ncentus** [nodef/extra-number#12]
https://javascript.plainenglish.io/4-reasons-why-var-is-considered-obsolete-in-modern-javascript-a30296b5f08f

using var is mainly for support old browser => compiler is for that, so you need some knowledge on tsconf.json
**using "var" is "deprecated" since a decade now ... even in a javascript files.**

https://caniuse.com/?search=let 
97% running users browsers nowadays support "let"
99% for "const"

some devs convainced that compilers is less and less valuable  for cross browser compabilities ...
![image](https://user-images.githubusercontent.com/25374826/232232037-2b3fc5e7-5be3-44ff-9370-5256219a600d.png)

**Comment by wolfram77** [comment]
@c0ncentus Is this causing any issue?
